---
title: "Phils Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(ggplot2)
library(dplyr)
library(plotly)


library(readr)
adae <- read_csv("https://rhoinc.github.io/data-library/data/clinical-trials/adam/adae.csv")

adae

new_adae <- adae %>%
 filter(!(SITE %in% "Clinical Site 01")) %>%
 filter(!(ARM %in% "Screen Failure")) 

new_adae

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
dv1 <- ggplot(new_adae) +
 aes(x = AESEV, fill = SEX) +
 geom_bar() +
 scale_fill_hue(direction = 1) +
 theme_minimal()

ggplotly(dv1)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
dv2 <- ggplot(new_adae) +
 aes(x = AESEV, weight = AGE) +
 geom_bar(fill = "#112446") +
 theme_minimal() +
 facet_wrap(vars(SEX))

ggplotly(dv2)
```

### Chart C

```{r}
dv3 <- ggplot(new_adae) +
 aes(x = AESEV, fill = ARM) +
 geom_bar() +
 scale_fill_hue(direction = 1) +
 coord_flip() +
 theme_minimal()

ggplotly(dv3)
```

